name: gp_2025_11
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase - آخر إصدارات متوافقة مع Java 17
  firebase_core: ^3.15.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.0
  
  # باقي المكتبات
  image_picker: ^1.1.2
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true